# Generated by Django 2.0.5 on 2018-05-12 03:41

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=32, verbose_name='商品名称')),
                ('gpic', models.ImageField(upload_to='goods', verbose_name='商品图片')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('idDelete', models.BooleanField(default=False)),
                ('gunit', models.CharField(default='500g', max_length=32)),
                ('gclick', models.IntegerField()),
                ('gjianjie', models.CharField(max_length=256)),
                ('gkucun', models.IntegerField()),
                ('gcontent', DjangoUeditor.models.UEditorField(verbose_name='详细信息')),
                ('gadv', models.BooleanField(default=False, verbose_name='广告位')),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=32)),
                ('isDelete', models.BooleanField(max_length=False)),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.TypeInfo'),
        ),
    ]
