# Generated by Django 2.0.5 on 2018-05-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=32)),
                ('upwd', models.CharField(max_length=64)),
                ('uemail', models.CharField(max_length=32)),
                ('ushou', models.CharField(default='', max_length=32)),
                ('uaddress', models.CharField(default='', max_length=128)),
                ('uyoubian', models.CharField(default='', max_length=8)),
                ('uphone', models.CharField(default='', max_length=11)),
            ],
        ),
    ]
